name: V2Ray Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Building and Deploying
      run: |
        docker run -d --name v2ray -p 80:8080 v2fly/v2fly-core
        sleep 10
        docker exec v2ray v2ray-core -c /etc/v2ray/config.json &
        UUID=$(docker exec v2ray v2ray-core api stats --server=127.0.0.1:10085 | grep -o -E 'id: "[^"]+"' | cut -d'"' -f2)
        IP=$(curl -s ifconfig.me)
        VMESS_CONFIG="{\"v\":\"2\",\"ps\":\"GitHub-Action\",\"add\":\"$IP\",\"port\":\"80\",\"id\":\"$UUID\",\"aid\":\"0\",\"net\":\"tcp\",\"type\":\"none\",\"host\":\"\",\"path\":\"\",\"tls\":\"\"}"
        VMESS_URL="vmess://$(echo -n $VMESS_CONFIG | base64 -w 0)"
        echo "=================================================="
        echo "VMESS URL: $VMESS_URL"
        echo "=================================================="
        sleep 36000
